#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# Only showing username:user id:home directory path for the user.

FILE="/etc/passwd"

while IFS= read -r line
do
    echo "$line" | cut -d ":" -f1,3,6
done < "$FILE"
